### ISSUE TITLE
Output as texture map

### ISSUE THREAD

**Issue by deuemort** [inverse-neural-radiosity/inverse-neural-radiosity#2]
Thank you for sharing your great work.
This is a question, not a bug report.
Is there any way to obtain an albedo texture map per mesh object from the learned MLP so that it can be imported into Blender?

**Comment by logchan** [comment]
Our method and code model SVBRDF parameters as varying in 3D space (usually evaluated at hit points of rays), without knowledge of mesh or uv coordinates. Therefore, we can't directly obtain mesh textures.

There may be ways to workaround this, below are some of my unverified thoughts:

One can render albedo images, then manually crop and align in Blender. This probably only work for simple geometry.

One can also try training an MLP at uv coordinates, e.g. create a variant of `MyTexture` ([link](https://github.com/inverse-neural-radiosity/inverse-neural-radiosity/blob/6af9428cad36a01b571fa9660317298952514548/nerad/texture/mytexture.py#L35)) to pass `si.prim_index` and `si.uv` instead of `si.p`, and a corresponding MLP model.

**Comment by deuemort** [comment]
@logchan 
Thank you for the answer, and your second idea sounds interesting.
I will try to obtain texture maps in some way.
